[[configuration]]
== Configuration

The plugin provide a default configuration, but you may add your own settings in your *Config.groovy* for Grails 2.x and *application.groovy* or *application.yml* for Grails 3.x.

=== Overriding Spring Boot elasticsearch version

Spring Boot 1.3.x supports Elasticsearch 1.5.2 OOTB (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L76) and will install dependencies for this version, if not explicitly overriden.
To do so add the following to your `build.gradle`:

[source,groovy]
----
def elasticsearchVersion = '5.4.3'
ext['elasticsearch.version'] = elasticsearchVersion
----

=== Default configuration script

Below is the default configuration loaded by the plugin (any of your settings in the Config.groovy script overwrite those).

[source,groovy]
.Config.groovy
----
elasticSearch {
  /**
   * Date formats used by the unmarshaller of the JSON responses
   */
  date.formats = ["yyyy-MM-dd'T'HH:mm:ss'Z'"]

  /**
   * Hosts for remote ElasticSearch instances.
   */
  client.hosts = [
          [host:'localhost', port:9300]
  ]

  /**
   * Default mapping property exclusions
   *
   * No properties matching the given names will be mapped by default
   * i.e., when using "searchable = true"
   *
   * This does not apply for classes using mapping by closure
   */
  defaultExcludedProperties = ["password"]

  /**
   * Determines if the plugin should reflect any database save/update/delete automatically
   * on the ES instance. Default to false.
   */
  disableAutoIndex = false

  /**
   * Should the database be indexed at startup.
   *
   * The value may be a boolean true|false.
   * Indexing is always asynchronous (compared to Searchable plugin) and executed after BootStrap.groovy.
   */
  bulkIndexOnStartup = true

  /**
   *  Max number of requests to process at once. Reduce this value if you have memory issue when indexing a big amount of data
   *  at once. If this setting is not specified, 500 will be use by default.
   */
  maxBulkRequest = 500


  /**
   * The name of the ElasticSearch mapping configuration property that annotates domain classes. The default is 'searchable'.
   */
  searchableProperty.name = 'searchable'
}

environments {
  development {
    /**
     * Possible values : "local", "dataNode", "transport"
     *
     */
    elasticSearch.client.mode = 'local'
  }
  test {
      elasticSearch {
          client.mode = 'local'
          index.store.type = 'fs'
      }
  }
}
----

==== Grails 3.3.x Sample YAML configuration

[source,yaml]
.application.yml
----
elasticSearch:
  date:
    formats: ["yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"]
  client:
    connectTimeout: 2
    socketTimeout: 30
    mode: local
    hosts:
      - {host: localhost, port: 9200}
    transport.sniff: false
    username: zzb-elasticsearch
    password: /+mh&K@2sF('X7J_
  datastoreImpl: hibernateDatastore
  defaultExcludedProperties: ['password']
  disableAutoIndex: false
  index:
    compound_format: true
    store.type: fs
    settings:
      analysis:
        filter:
          replace_synonyms:
            type: synonym
            synonyms: ['abc => xyz']
        analyzer:
          test_analyzer:
            tokenizer: standard
            filter: ['lowercase']
          repl_analyzer:
            tokenizer: standard
            filter: ['lowercase', 'replace_synonyms']
  snapshots:
    repository:
      name: ss_repo
      config:
        type: fs
        settings:
          ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html for all params
          location: snapshots
          compress: false
          chunk_size: 20MB
    policies:
      - id: nightly-snapshots
        config:
          schedule: "0 30 1 * * ?"
          name: "<nightly-snap-{now/d}>"
          repository: "ss_repo"
          config:
            indices: ["*"]
            retention:
              expire_after: "30d"
              min_count: 5
              max_count: 50
      - id: hourly-snapshots
        config:
          schedule: "0 0 */1 * * ?"
          name: "<hourly-snap-{now/d}>"
          repository: "ss_repo"
          config:
            indices: ["*"]
            retention:
              expire_after: "1d"
              min_count: 5
              max_count: 24

  unmarshallComponents: true
  searchableProperty:
    name: searchable
  includeTransients: false
  includeDomainTypeName: true

environments:
  production:
    elasticSearch:
      client:
        mode: node
----

=== Mapping Migration properties

Define the application's behaviour when a conflict is found while installing Elasticsearch mappings on startup.
For a detailed explanation, see <<Mapping Migrations>>.

==== `elasticSearch.migration.strategy`

Defines the behaviour to follow if an error occurs on startup when the application is installing new mappings on ElasticSearch due to conflicting mappings.

.Possible Values for migration strategy
[width="100%",cols="2",options="header"]
|===
|Value |Description

| `'none'`
|No changes on the indices or mappings will happen, the merge problem will be logged and a MappingException will be thrown.

| `'delete'`
|The conflicting mapping will be deleted (along with all indexed content of that type) and replaced with a new mapping. Deleted content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option

| `'alias'`
|Applies http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/[Elasticsearch recommended approach for migrating conflicting mappings]. A new numbered index will be created (`<indexName>_vX`) where new mappings will installed for all the types included on the original index. An Elasticsearch alias called `<indexName>` will point to the new index. As content won't be available on the new index, content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option. It is recommended to set `elasticSearch.aliasReplacesIndex` to deal with potential index/alias conflicts.

|===

[NOTE]
====
The default is `'alias'`.
====

==== `elasticSearch.migration.aliasReplacesIndex`

Deals with a special conflict case using the `'alias'` strategy.
When the `'alias'` migration strategy is chosen and there's a mapping conflict on an index, defines whether to replace the index with a versioned index (`<indexName>_vX`) and an alias (`<indexName>`).
This is required when applying the alias strategy on top of existing indices for the first time as indices cannot be renamed (from `<indexName>` to `<indexName>_vX`) and an alias cannot exist with the same name as an index.

.Possible Values for aliasReplacesIndex
[width="100%",cols="2",options="header"]
|===
|Value| Description

| `true`
| The index and it's content will be deleted and a versioned index and an alias will be created. Deleted content can be automatically reindexed on startup by using this in combination the `elasticSearch.bulkIndexOnStartup` config option

| `false`
| Falls back to the `'none'` strategy. Event will be logged and a MappingException will be thrown.

|===	

[NOTE]
====
The default is `true`.
====

==== `elasticSearch.migration.disableAliasChange`

In some cases the developer may prefer not to upgrade the alias to the new version of the index until some other tasks are performed.
This allows them to disable automatically pointing the alias to a new version of the index when this is created.
Aliases can be changed later on manually or programatically using `elasticSearchAdminService`

.Possible Values for disableAliasChange
[width="100%",cols="2",options="header"]
|===
| Value | Description

| `false`
| Standard behaviour

| `true`
| Prevents the aliases to be changed to point to a new index
|===

[NOTE]
====
The default is `false`.
====

=== Dynamic Method Injection

==== `elasticSearch.searchMethodName`

Change the name of search method in domain class.
By default it's `search`.

For example

[source,groovy]
----
MyDomain.search("${params.query}")

----

[TIP]
====
In order to change the method name to `esSearch` just update the `elasticSearch.searchMethodName='esSearch'` in application.groovy
====

==== `elasticSearch.countHitsMethodName`

Change the name of countHits method in domain class.
By default it's `countHits`.

For example

[source,groovy]
----
MyDomain.countHits("${params.query}")

----

[TIP]
====
In order to change the method name to `esCountHits` just update the `elasticSearch.countHitsMethodName='esCountHits'` in application.groovy
====

==== `elasticSearch.disableDynamicMethodsInjection`

To complete disabled injection of dynamic methods set `elasticSearch.disableDynamicMethodsInjection = true` in `applicaiton.groovy`

=== Others properties

==== `elasticSearch.datastoreImpl`

Only required when enabling the auto-index feature.
This property specifies which GORM datastore implementation should be watched for storage events.
The value should be the name of the datastore bean as it is configured in the Spring context; some possible values:

.Possible Values for datastoreImpl
[width="100%",cols="2",options="header"]
|===
| Value | Description

| mongoDatastore
| The name of the MongoDB datastore bean.

| hibernateDatastore
| The name of the Hibernate datastore bean.

|===

==== `elasticSearch.bootstrap.config.file`

When using then plugin to construct a local node, the default Elasticsearch configuration is used by default.
If you use a modified Elasticsearch configuration, you can use this property to specify the location of the file (as an application resource).

==== `elasticSearch.bootstrap.transportSettings.file`

When choosing transport mode this configuration will be used to set up the TransportClient settings (used by some cloud providers).

==== `elasticSearch.client.transport.sniff`

Only usable in with a transport client.
Allows to sniff the rest of the cluster, and add those into its list of machines to use.
In this case, the ip addresses used will be the ones that the other nodes were started with (the “publish” address)

==== `elasticSearch.cluster.name`

The name of the cluster for the client to join.

==== `elasticSearch.date.formats`

List of date formats used by the JSON unmarshaller to parse any date field properly.
Note : future version of the plugin may change how formats are manipulated.

==== `elasticSearch.defaultExcludedProperties`

List of domain class properties to automatically ignore (will not be indexed) if their name match one of those.
This will apply to both the default-mapped domain class, with the static `searchable` property set to "true", and when using closure mapping.
To override this setting on a specific class, it can be added to the `only` property of the `searchable` closure.

==== `elasticSearch.disableAutoIndex`

A boolean determining if the plugin should reflect any database save/update/delete automatically on the indices.
Default to `false`.

==== `elasticSearch.bulkIndexOnStartup`

Determines whether the application should launch a bulk index operation upon startup.

.Possible Values for bulkIndexOnStartup
[width="100%",cols="2",options="header"]
|===
| Value | Description

| `false`
| No indexing will happen on startup.

| `true`
| All content will be indexed on startup.

| `'deleted'`
| This value is related to the mapping migration strategy chosen. If any migration is required and any content is deleted due to it, on startup only indices and mappings lost will be indexed. More on <<Mapping Migrations>>.
|===

[NOTE]
====
Default to `true`.
====

==== `elasticSearch.index.name`

A string indicating which ElasticSearch index should be used.
If not present, will default to the package name of the domain in question.

[NOTE]
====
From Elasticsearch 5.0 on only selected settings like for instance index.codec can be set on the node level.
All other settings must be set on each individual index.
To set default values on every index, index templates should be used instead.
So, unset this value if you are using Elasticsearch v5.0 or above.
====

==== `elasticSearch.index.compound_format`

Should the compound file format be used (boolean setting).
Set to `false` by default (really applicable for file system based index storage).
More details on this setting on the http://www.elasticsearch.org/guide/reference/index-modules/[ElasticSearch Documentation].

==== `elasticSearch.index.store.type`

Determine how the indices will be stored.
More details on the possible values on the http://www.elasticsearch.org/guide/reference/index-modules/store.html[ElasticSearch Documentation].

.Possible value for index store type
[width="100%",cols="2",options="header"]
|===
| Value | Description

| fs
| Default file system implementation. This will pick the best implementation depending on the operating environment, which is currently hybridfs on all supported systems but is subject to change.

| simplefs
| The Simple FS type is a straightforward implementation of file system storage (maps to Lucene SimpleFsDirectory) using a random access file. This implementation has poor concurrent performance (multiple threads will bottleneck) and disables some optimizations for heap memory usage.

| niofs
| The NIO FS type stores the shard index on the file system (maps to Lucene NIOFSDirectory) using NIO. It allows multiple threads to read from the same file concurrently. It is not recommended on Windows because of a bug in the SUN Java implementation and disables some optimizations for heap memory usage.

| mmapfs
| The MMap FS type stores the shard index on the file system (maps to Lucene MMapDirectory) by mapping a file into memory (mmap). Memory mapping uses up a portion of the virtual memory address space in your process equal to the size of the file being mapped. Before using this class, be sure you have allowed plenty of virtual address space.

| hybridfs
| The hybridfs type is a hybrid of niofs and mmapfs, which chooses the best file system type for each type of file based on the read access pattern. Currently only the Lucene term dictionary, norms and doc values files are memory mapped. All other files are opened using Lucene NIOFSDirectory. Similarly to mmapfs be sure you have allowed plenty of virtual address space.

|===

==== `elasticSearch.index.settings.numberOfReplicas`

Sets the number of replicas created for each shard of the index.
If not present, will default to zero.

==== `elasticSearch.gateway.type`

Determine the gateway type to be used.
More details on the possible values are in the http://www.elasticsearch.org/guide/reference/modules/gateway/[ElasticSearch Documentation].
Using a setting of "none" (possibly in combination with index.store.type set to "memory") can be useful for tests.

==== `elasticSearch.maxBulkRequest`

Max number of requests to process at once.
Reduce this value if you have memory issue when indexing a big amount of data at once.
If this setting is not specified, 500 will be use by default.

==== `elasticSearch.path.data`

The location of the data files of each index / shard allocated on the node.

==== `elasticSearch.path.plugins`

The location of plugin files such as native scripts.
Each plugin will be contained in a subdirectory.

==== `elasticSearch.searchableProperty.name`

The name of the ElasticSearch mapping configuration property that annotates domain classes.
The default is 'searchable'.

==== `elasticSearch.includeTransients`

Whether to index and search all non excluded transient properties.
All explicitly included transients in `only` will be indexed regardless.

[NOTE]
====
Default is `false`.
====
