=== Plugin Versioning

[NOTE]
====
The versioning model has changed.
The version number of the plugin will reflect the one of the underline integrated Elasticsearch.
If necessary a 4th level point release number will be used for successive changes on the plugin's code with same version of Elasticsearch.
====

`<GRAILS_VERSION>.<ES_VERSION>.<FEATURE/PATCH_VERSION>`, where there isn't really a 1-to-1 plugin version to grails or es version, but we just increase our major or minor version by one, whenever there are breaking changes on either Grails or ES.
`<GRAILS_VERSION>.<ES_VERSION>.<FEATURE/PATCH_VERSION>`, where there isn't really a 1-to-1 plugin version to grails or es version, but we just increase our major or minor version by one, whenever there are breaking changes on either Grails or ES. Therefore future release versions could look something similar to this (depending on Grails and Elasticsearch versions):

|===
s| Plugin Version   s| Grails                s| Elasticsearch
| 2.8.0 (wip)        | 4.0.x                  | 7.7.x
| 2.7.5-SNAPSHOT     | 3.3.x                  | 7.7.x
s| 2.7.5            s| 3.3.x                 s| 7.7.x
| 2.7.4              | 3.3.x                  | 7.7.x
| 2.7.3              | 3.3.x                  | 7.6.x
| 2.7.2              | 3.3.x                  | 7.x
|===

_Existing versions in_ *bold*

The current version is *{revnumber}* (for Grails 2.x the latest version is *0.1.0*)